org: techgrowthlabs
app: conversales-api
service: conversales-api
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  # - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  stage: dev
  # profile: serverless

functions:
  webhook-whatsapp:
    handler: src/webhook/index.whatsapp
    events:
      - httpApi:
          path: /{companyId}/webhook/whatsapp
          method: post

  webhook-telegram:
    handler: src/webhook/index.telegram
    timeout: 30
    events:
      - httpApi:
          path: /{companyId}/webhook/telegram
          method: post

  set-webhook:
    handler: src/webhook/index.setEfiWebhook
    events:
      - httpApi:
          path: /webhook/{companyId}/{hmac}
          method: post

  pix-webhook:
    handler: src/webhook/index.pix
    events:
      - httpApi:
          path: /webhook/{companyId}/{hmac}/pix
          method: post

  retry-contact:
    handler: src/webhook/index.retryContact
    timeout: 30
    events:
      - httpApi:
          path: /retry-contact/{ticketId}
          method: post

  find-tickets:
    handler: src/webhook/index.findTickets
    events:
      - httpApi:
          path: /ticket
          method: get

  send-contact-message:
    handler: src/webhook/index.sendContactMessage
    events:
      - httpApi:
          path: /send-contact-message
          method: post

  # find-all-tickets:
  #   handler: src/ticket/index.findAll
  #   events:
  #     - httpApi:
  #         path: /ticket
  #         method: get

package:
  # individually: true
  include:
    - certify.p12
# custom:
#   customDomain:
#     domainName: api.conversales.techgrowth-labs.com.br

#     endpointType: REGIONAL

#     apiType: http
#     certificateArn: arn:aws:acm:sa-east-1:779846802300:certificate/18c6ffb0-e642-471a-bd7e-2b749c00cc9b
