org: techgrowthlabs
app: conversales-api
service: conversales-api
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  stage: dev
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowCredentials: false
      allowedMethods:
        - OPTIONS
        - GET
        - POST
      allowedHeaders:
        - Content-Type
        - x-api-key

functions:
  webhook-whatsapp-validation:
    handler: src/webhook/index.whatsappValidation
    events:
      - httpApi:
          path: /{companyId}/webhook/whatsapp
          method: get

  webhook-whatsapp:
    handler: src/webhook/index.whatsapp
    timeout: 30
    events:
      - httpApi:
          path: /{companyId}/webhook/whatsapp
          method: post

  webhook-telegram:
    handler: src/webhook/index.telegram
    timeout: 30
    events:
      - httpApi:
          path: /{companyId}/webhook/telegram
          method: post

  set-webhook:
    handler: src/webhook/index.setEfiWebhook
    events:
      - httpApi:
          path: /webhook/{companyId}/{hmac}
          method: post

  pix-webhook:
    handler: src/webhook/index.pix
    events:
      - httpApi:
          path: /webhook/{companyId}/{hmac}/pix
          method: post

  retry-contact:
    handler: src/webhook/index.retryContact
    timeout: 30
    events:
      - httpApi:
          path: /retry-contact/{ticketId}
          method: post

  find-tickets:
    handler: src/webhook/index.findTickets
    events:
      - httpApi:
          path: /ticket
          method: get

  send-contact-message:
    handler: src/webhook/index.sendContactMessage
    events:
      - httpApi:
          path: /send-contact-message
          method: post

package:
  excludeDevDependencies: true
  individually: true
  include:
    - certify.p12
