export enum StepFunctions {
	LIST_PRODUCTS = "LIST_PRODUCTS",
	ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART",
	GET_CHECKOUT = "GET_CHECKOUT",
	CLEAN_CART = "CLEAN_CART",
	GET_PAYMENT = "GET_PAYMENT",
	SEND_MESSAGE_TO_GPT = "SEND_MESSAGE_TO_GPT",
	VALIDATE_EMAIL = "VALIDATE_EMAIL",
	VALIDATE_CNPJ = "VALIDATE_CNPJ",
}
